### ISSUE TITLE
Which Platform?

### ISSUE THREAD

**Issue by amaliujia** [flode/BwTree#1]
Hi,

I am trying to compile your code. But I failed both on os x and ubuntu platform.

The make errors were similar: "error: invalid value 'c++14' in '-std=c++14'".

Can you tell me which platform did you use to compile the code?

**Comment by flode** [comment]
I am using Ubuntu 15.10 with gcc 5.2.1. The error message looks like you are using a compiler that does not support C++ 14 yet.

**Comment by amaliujia** [comment]
Thanks!
