### ISSUE TITLE
Updating the mapping table

### ISSUE THREAD

**Issue by MayankSur** [flode/BwTree#2]
Hi,

I've noticed that during your inserts and deletes you create a new node for delta insert and delta delete, but you never update the mapping table to point to the new node, as far as I can see.

Would you be able to explain, where this happens?

**Comment by flode** [comment]
Hi, this happens with the compare_exchange_weak call on the atomic. It alters the state of mapping while guaranteeing that other threads don't interfere.

**Comment by MayankSur** [comment]
Hi, 

That's great, I was removing all components to run it without threads and that must have lead to an issue. 

Cheers for the help.
